import os
from dotenv import load_dotenv

load_dotenv()

APP_ENV = os.getenv("APP_ENV", "dev")
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_CHAT_DEPLOYMENT = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT")
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = os.getenv(
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT"
)

AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_INDEX_NAME = os.getenv("AZURE_SEARCH_INDEX_NAME")
AZURE_SEARCH_API_KEY = os.getenv("AZURE_SEARCH_API_KEY")

AZURE_ENTRA_TENANT_ID = os.getenv(
    "AZURE_ENTRA_TENANT_ID"
)

AZURE_ENTRA_API_CLIENT_ID = os.getenv(
    "AZURE_ENTRA_API_CLIENT_ID"
)

AZURE_ENTRA_TEST_CLIENT_ID = os.getenv(
    "AZURE_ENTRA_TEST_CLIENT_ID"
)

AZURE_CONTENT_SAFETY_ENDPOINT = os.getenv(
    "AZURE_CONTENT_SAFETY_ENDPOINT"
)

AZURE_CONTENT_SAFETY_API_KEY = os.getenv(
    "AZURE_CONTENT_SAFETY_API_KEY"
)

AZURE_CONTENT_SAFETY_BLOCKLIST_NAME = os.getenv(
    "AZURE_CONTENT_SAFETY_BLOCKLIST_NAME"
)

AZURE_COSMOS_ENDPOINT = os.getenv(
    "AZURE_COSMOS_ENDPOINT"
)

AZURE_COSMOS_DATABASE_NAME = os.getenv(
    "AZURE_COSMOS_DATABASE_NAME"
)

AZURE_COSMOS_SESSION_CONTAINER_NAME = os.getenv(
    "AZURE_COSMOS_SESSION_CONTAINER_NAME"
)